# Generated by Django 5.2.17 on 2026-08-10 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('name', models.TextField()),
                ('slug', models.TextField()),
                ('description', models.TextField(null=True)),
                ('images', models.JSONField(default=list)),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'assets',
                'managed': True,
            },
        ),
    ]
