FROM node:20-alpine

WORKDIR /app
ENV NODE_ENV=production

COPY package.json package-lock.json ./
RUN npm ci --include=dev

COPY jsconfig.json ./
COPY src ./src

CMD ["npm", "run", "worker:generation"]
