# Generated by Django 5.2.17 on 2026-08-10 08:02

import uuid
from django.db import migrations, models

# See apps/common/db_flags.py.
from apps.common.db_flags import TEST_MANAGED


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('role', models.TextField(default='user')),
                ('color', models.TextField(null=True)),
                ('avatar_url', models.TextField(db_column='avatar_url', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('auth_version', models.IntegerField(db_column='auth_version', default=0)),
                ('created_at', models.BigIntegerField(db_column='created_at')),
            ],
            options={
                'db_table': 'users',
                'managed': TEST_MANAGED,
            },
        ),
    ]
