# Generated by Django 5.2.17 on 2026-08-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.TextField(db_column='password_hash', default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='password_salt',
            field=models.TextField(db_column='password_salt', default=''),
        ),
    ]
