# Generated by Django 5.2.17 on 2026-08-10 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_user_password_hash_user_password_salt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(null=True)),
                ('action', models.TextField()),
                ('detail', models.JSONField(null=True)),
                ('created_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'activity_logs',
                'managed': True,
            },
        ),
    ]
