# Generated by Django 5.2.17 on 2026-08-10 12:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField()),
                ('name', models.TextField()),
                ('kind', models.TextField(default='chat')),
                ('agent_kind', models.TextField(null=True)),
                ('created_by', models.UUIDField(null=True)),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'agent_conversations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AgentConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('conversation_id', models.UUIDField()),
                ('role', models.TextField()),
                ('content', models.TextField()),
                ('tool_trace', models.JSONField(null=True)),
                ('created_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'agent_conversation_messages',
                'managed': True,
            },
        ),
    ]
