# Generated by Django 5.2.17 on 2026-08-10 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('status', models.TextField()),
                ('prompt', models.TextField()),
                ('model', models.TextField()),
                ('aspect_ratio', models.TextField()),
                ('resolution', models.TextField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('url', models.TextField(null=True)),
                ('poster', models.TextField(null=True)),
                ('error', models.TextField(null=True)),
                ('moderation_blocked', models.BooleanField(null=True)),
                ('reference_images', models.JSONField(null=True)),
                ('reference_videos', models.JSONField(null=True)),
                ('project_id', models.UUIDField(null=True)),
                ('folder_id', models.UUIDField(null=True)),
                ('user_id', models.UUIDField(null=True)),
                ('cost_cents', models.IntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('favorited_at', models.BigIntegerField(null=True)),
                ('task_id', models.TextField(null=True)),
                ('generate_audio', models.BooleanField(null=True)),
                ('video_task_mode', models.TextField(null=True)),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'generations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('model', models.TextField(db_column='model', primary_key=True, serialize=False)),
                ('unit_cost_cents', models.IntegerField()),
                ('unit', models.TextField()),
                ('notes', models.TextField(null=True)),
            ],
            options={
                'db_table': 'pricing',
                'managed': True,
            },
        ),
    ]
