# Generated by Django 5.2.17 on 2026-08-14 06:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepthWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('worker_id', models.TextField(unique=True)),
                ('label', models.TextField(null=True)),
                ('device', models.TextField(null=True)),
                ('status', models.TextField(default='idle')),
                ('current_job_id', models.UUIDField(null=True)),
                ('ram_limit_mb', models.IntegerField(null=True)),
                ('ram_used_mb', models.IntegerField(null=True)),
                ('last_seen_at', models.BigIntegerField()),
                ('created_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'depth_workers',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='generation',
            name='progress_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='progress_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='track_characters',
            field=models.BooleanField(null=True),
        ),
    ]
