# Generated by Django 5.2.17 on 2026-08-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_depthworker_generation_progress_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='seed',
            field=models.IntegerField(null=True),
        ),
    ]
