# Generated by Django 5.2.17 on 2026-08-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_generation_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='candidate_task_ids',
            field=models.JSONField(null=True),
        ),
    ]
