# Generated by Django 5.2.17 on 2026-08-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0004_generation_candidate_task_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='continuation_frame_url',
            field=models.TextField(null=True),
        ),
    ]
