# Generated by Django 5.2.17 on 2026-08-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0005_generation_continuation_frame_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='flag_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generation',
            name='flagged_at',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='judge_score',
            field=models.JSONField(null=True),
        ),
    ]
