# Generated by Django 5.2.17 on 2026-08-10 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField()),
                ('name', models.TextField()),
                ('data', models.JSONField()),
                ('created_by', models.UUIDField(null=True)),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'canvas_boards',
                'managed': True,
            },
        ),
    ]
